const { Game } = require("../models");

const gameData = [
  {
    words: "Belly, Beer, Flop",
    compoundled: "Beer, Belly, Flop",
    correct_order: "1,0,2",
    hidden_word: null,
    points: 300,
    level: 1,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Stakes, Sweep, Chimney",
    compoundled: "Chimney, Sweep, Stakes",
    correct_order: "2,1,0",
    hidden_word: null,
    points: 300,
    level: 2,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Variety, Garden, Show",
    compoundled: "Garden, Variety, Show",
    correct_order: "1,0,2",
    hidden_word: null,
    points: 300,
    level: 3,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Red, Table, Water, Hot",
    compoundled: "Red, Hot, Water, Table",
    correct_order: "0,3,2,1",
    hidden_word: null,
    points: 400,
    level: 4,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Box, Rain, Check, Cutter",
    compoundled: "Rain, Check, Box, Cutter",
    correct_order: "1,2,0,3",
    hidden_word: null,
    points: 400,
    level: 5,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "War, Fighter, Flame, Crime",
    compoundled: "Flame, War, Crime, Fighter",
    correct_order: "2,0,3,1",
    hidden_word: null,
    points: 400,
    level: 6,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Good, Feel, Out, Luck, Last",
    compoundled: "Feel, Good, Luck, Out, Last",
    correct_order: "1,0,3,2,4",
    hidden_word: null,
    points: 500,
    level: 7,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Work, Search, Paint, Job, Team",
    compoundled: "Paint, Job, Search, Team, Work",
    correct_order: "2,3,1,4,0",
    hidden_word: null,
    points: 500,
    level: 8,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Full, Shot, Moon, Up, Beam",
    compoundled: "Full, Moon, Beam, Up, Shot",
    correct_order: "0,2,4,3,1",
    hidden_word: null,
    points: 500,
    level: 9,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Come, Sense, Animal, Back, Kingdom, Talk",
    compoundled: "Animal, Kingdom, Come, Back, Talk, Sense",
    correct_order: "2,4,0,3,5,1",
    hidden_word: null,
    points: 600,
    level: 10,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Last, Encounter, Chance, Fake, Out, Pump",
    compoundled: "Pump, Fake, Out, Last, Chance, Encounter",
    correct_order: "5,3,4,0,2,1",
    hidden_word: null,
    points: 600,
    level: 11,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Principle, Best, Law, Case, Abiding, Reason",
    compoundled: "Best, Case, Law, Abiding, Principle, Reason",
    correct_order: "1,3,2,4,0,5",
    hidden_word: null,
    points: 600,
    level: 12,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Paper, Saint, Airplane, Patron, Wall, Hanger, Paul",
    compoundled: "Patron, Saint, Paul, Wall, Paper, Airplane, Hanger",
    correct_order: "3,1,6,4,0,2,5",
    hidden_word: null,
    points: 700,
    level: 13,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Market, Off, Suit, Cap, Jacket, Track, Farmers",
    compoundled: "Farmers, Market, Cap, Off, Track, Suit, Jacket",
    correct_order: "6,0,3,1,5,2,4",
    hidden_word: null,
    points: 700,
    level: 14,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Shoot, Move, Smart, Trouble, Daily, Out, Double",
    compoundled: "Daily, Double, Trouble, Shoot, Out, Smart, Move",
    correct_order: "4,6,3,0,5,2,1",
    hidden_word: null,
    points: 700,
    level: 15,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Swimming, , Table",
    compoundled: "Swimming, Pool, Table",
    correct_order: "0,1,2",
    hidden_word: "pool",
    points: 700,
    level: 16,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Dancer, Mister, , Hey, Bean, Peanut, Pole",
    compoundled: "Hey, Mister, Peanut, Butter, Bean, Pole, Dancer",
    correct_order: "3,1,5,2,4,6,0",
    hidden_word: "butter",
    points: 1000,
    level: 17,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Flash, Game, Woman, Card, Boy, Board, ",
    compoundled: "Flash, Card, Board, Game, Boy, Wonder, Woman",
    correct_order: "0,3,5,1,4,6,2",
    hidden_word: "wonder",
    points: 1000,
    level: 18,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "High, Stadium, Area, Flying, Seating, , Fantasy",
    compoundled: "Flyiing, High, Fantasy, Football, Stadium, Seating, Area",
    correct_order: "3,0,6,5,1,4,2",
    hidden_word: "football",
    points: 1000,
    level: 19,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Lava, Bad, Red, Blood, , Hot, Shade",
    compoundled: "Bad, Blood, Red, Hot, Lava, Lamp, Shade",
    correct_order: "1,3,2,5,0,4,6",
    hidden_word: "lamp",
    points: 1000,
    level: 20,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: ", People, Down, Square, Low, Party, Dance",
    compoundled: "Low, Down, Town, Square, Dance, Party, People",
    correct_order: "4,2,0,3,6,5,1",
    hidden_word: "town",
    points: 1000,
    level: 21,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Hole, Yellow, Walk, Belly, , Man, Fat",
    compoundled: "Yellow, Belly, Fat, Cat, Walk, Man, Hole",
    correct_order: "1,3,6,4,2,5,0",
    hidden_word: "cat",
    points: 1000,
    level: 22,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Banana, , Phone, Case, Cabinet, File, Storage",
    compoundled: "Banana, Phone, Book, Case, File, Storage, Cabinet",
    correct_order: "0,2,1,3,5,6,4",
    hidden_word: "book",
    points: 1000,
    level: 23,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Lands, Step, Zone, Bad, Breaking, , End",
    compoundled: "Step, Back, Breaking, Bad, Lands, End",
    correct_order: "1,5,4,3,0,6,2",
    hidden_word: "back",
    points: 1000,
    level: 24,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Sugar, Candy, Daddy, Thick, , Cane, Issues",
    compoundled: "Thick, Skull, Candy, Cane, Sugar, Daddy, Issues",
    correct_order: "3,4,1,5,0,2,6",
    hidden_word: "skull",
    points: 1000,
    level: 25,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Front, Weather, , Door, Up, Mountain, Man",
    compoundled: "Mountain, Man, Up, Front, Door, Bell, Weather",
    correct_order: "5,6,4,0,3,2,1",
    hidden_word: "bell",
    points: 1000,
    level: 26,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Child, Man, Chart, Care, One, , Work",
    compoundled: "One, Man, Child, Care, Work, Flow, Chart",
    correct_order: "4,1,0,3,6,5,2",
    hidden_word: "flow",
    points: 1000,
    level: 27,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Brush, Lay, , Low, Ring, Finger, Paint",
    compoundled: "Lay, Low, Key, Ring, Finger, Paint, Brush",
    correct_order: "1,3,2,4,5,6,0",
    hidden_word: "key",
    points: 1000,
    level: 28,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Carrot, Walk, Tale, Tall, Newborn, Cake, ",
    compoundled: "Newborn, Baby, Carrot, Cake, Walk, Tall, Tale",
    correct_order: "4,6,0,5,1,3,2",
    hidden_word: "baby",
    points: 1000,
    level: 29,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "School, Prep, Trip, Time, Day, , Meal",
    compoundled: "Time, Piece, Meal, Prep, School, Day, Trip",
    correct_order: "3,5,6,1,0,4,2",
    hidden_word: "piece",
    points: 1000,
    level: 30,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Golden, Card, Reader, Rule, Out, Side, ",
    compoundled: "Golden, Rule, Out, Side, Note, Card, Reader",
    correct_order: "0,3,4,5,6,1,2",
    hidden_word: "note",
    points: 1000,
    level: 31,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: ", Cake, Walk, Stick, Yard, Golden, Back",
    compoundled: "Golden, Birthday, Cake, Walk, Back, Yard, Stick",
    correct_order: "5,0,1,2,6,4,3",
    hidden_word: "birthday",
    points: 1000,
    level: 32,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Caps, , Tank, Top, Box, Out, Lock",
    compoundled: "Think, Caps, Lock, Box, Out, Tank, Top",
    correct_order: "0,6,4,5,1,2,3",
    hidden_word: "think",
    points: 1000,
    level: 33,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Free, , Bird, Spirit, Cage, Black, Swan",
    compoundled: "Black, Swan, Song, Bird, Cage, Free, Spirit",
    correct_order: "5,6,1,2,4,0,3",
    hidden_word: "song",
    points: 1000,
    level: 34,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: ", Yours, Home, Ball, Up, Smash, Hit",
    compoundled: "Smash, Hit, Home, Base, Ball, Up, Yours",
    correct_order: "5,6,2,0,3,4,1",
    hidden_word: "base",
    points: 1000,
    level: 35,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Cave, Harlem, Renaissance, Game, Board, Diving, ",
    compoundled: "Harlem, Renaissance, Man, Cave, Diving, Board",
    correct_order: "1,2,6,0,5,4,3",
    hidden_word: "man",
    points: 1000,
    level: 36,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Pen, , Brand, Loyal, Guinea, Name, New",
    compoundled: "New, Guinea, Pig, Pen, Name, Brand, Loyal",
    correct_order: "6,4,1,0,5,2,3",
    hidden_word: "pig",
    points: 1000,
    level: 37,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Basketball, True, , Ring, Crime, Professional, Consumate",
    compoundled: "Consumate, Professional, Basketball, Hoop, Ring, True, Crime",
    correct_order: "6,5,0,2,3,1,4",
    hidden_word: "hoop",
    points: 1000,
    level: 38,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Off, Bought, World, Department, , History, Old",
    compoundled: "Old, World, History, Department, Store, Bought, Off",
    correct_order: "6,2,5,3,4,1,0",
    hidden_word: "store",
    points: 1000,
    level: 39,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Instrument, , Landing, Wind, Frozen, Never, Almost",
    compoundled: "Almost, Never, Frozen, Stiff, Wind, Instrument, Landing",
    correct_order: "6,5,4,1,3,0,2",
    hidden_word: "stiff",
    points: 1000,
    level: 40,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Guitar, , String, Body, Electric, Celestial, Monger",
    compoundled: "Celestial, Body, Electric, Guitar, String, Cheese, Monger",
    correct_order: "5,3,4,0,2,1,6",
    hidden_word: "cheese",
    points: 1000,
    level: 41,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Blower, Red, Attack, Whistle, Surprise, October, ",
    compoundled: "Red, October, Surprise, Attack, Dog, Whistle, Blower",
    correct_order: "1,5,4,2,6,3,0",
    hidden_word: "dog",
    points: 1000,
    level: 42,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Out, Income, , Creep, Supplementary, Maneuver, Bracket",
    compoundled: "Supplementary, Income, Tax, Bracket, Creep, Out, Maneuver",
    correct_order: "4,1,2,6,3,0,5",
    hidden_word: "tax",
    points: 1000,
    level: 43,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Book, , League, Burning, Life, Bush, Saving",
    compoundled: "Life, Saving, Face, Book, Burning, Bush, League",
    correct_order: "4,6,1,0,3,5,2",
    hidden_word: "face",
    points: 1000,
    level: 44,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: ", Iron, Think, Eater, Mind, You, Man",
    compoundled: "Mind, You, Think, Big, Iron, Man, Eater",
    correct_order: "4,5,2,0,1,6,3",
    hidden_word: "big",
    points: 1000,
    level: 45,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Down, Stream, , Put, Coffee, Shot, Regular",
    compoundled: "Regular, Coffee, Mug, Shot, Put, Down, Stream",
    correct_order: "6,4,2,5,3,0,1",
    hidden_word: "mug",
    points: 1000,
    level: 46,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: ", Exit, Fire, Shave, Up, Ramp, Open",
    compoundled: "Open, Fire, Exit, Ramp, Up, Close, Shave",
    correct_order: "6,2,1,5,4,0,3",
    hidden_word: "close",
    points: 1000,
    level: 47,
    upload_date: "2023-11-06 11:30:00",
  },

  {
    words: "Part, Demon, , Time, Warp, Speed, Double",
    compoundled: "Double, Take, Part, Time, Warp, Speed, Demon",
    correct_order: "6,2,0,3,4,5,1",
    hidden_word: "take",
    points: 1000,
    level: 48,
    upload_date: "2023-11-06 11:30:00",
  },

  {
    words: "Age, End, New, Year, , Tennis, Gap",
    compoundled: "New, Age, Gap, Year, End, Table, Tennis",
    correct_order: "2,0,6,3,1,4,5",
    hidden_word: "table",
    points: 1000,
    level: 49,
    upload_date: "2023-11-06 11:30:00",
  },

  {
    words: "Throat, White, Bowl, Egg, Rice, , Goose",
    compoundled: "Goose, Egg, White, Rice, Bowl, Cut, Throat",
    correct_order: "6,3,1,4,2,5,0",
    hidden_word: "cut",
    points: 1000,
    level: 50,
    upload_date: "2023-11-06 11:30:00",
  },

  {
    words: "Fluid, Dynamics, , Pocket, Dead, Lighter, Drop",
    compoundled: "Drop, Dead, Air, Pocket, Lighter, Fluid, Dynamics",
    correct_order: "6,4,2,3,5,0,1",
    hidden_word: "air",
    points: 1000,
    level: 51,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Out, Buff, Fox, Movie, Comedy, , Hopeless",
    compoundled: "Hopeless, Romantic, Comedy, Movie, Buff, Out, Fox",
    correct_order: "6,5,4,3,1,0,2",
    hidden_word: "romantic",
    points: 1000,
    level: 52,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "General, , Morning, Attorney, Good, Glory, Practicing",
    compoundled: "Practicing, Attorney, General, Good, Morning, Glory",
    correct_order: "6,3,0,1,4,2,5",
    hidden_word: "public",
    points: 1000,
    level: 53,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Culture, Deep, , Clash, Mole, Freeze, Pop",
    compoundled: "Mole, Skin, Deep, Freeze, Pop, Culture, Clash",
    correct_order: "4,2,1,5,6,0,3",
    hidden_word: "skin",
    points: 1000,
    level: 54,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Up, Security, , Front, Times, Good, Desk",
    compoundled: "Good, Times, Up, Front, Desk, Job, Security",
    correct_order: "5,4,0,3,6,2,1",
    hidden_word: "job",
    points: 1000,
    level: 55,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Welfare, State, Play, Dead, Serious, , Minded",
    compoundled: "Welfare, State, Fair, Play, Dead, Serious, Minded",
    correct_order: "0,1,5,2,3,4,6",
    hidden_word: "fair",
    points: 1000,
    level: 56,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Greco, Roman, Stick, Figure, Drawing, Board, ",
    compoundled: "Greco, Roman, Candle, Stick, Figure, Drawing, Board",
    correct_order: "0,1,6,2,3,4,5",
    hidden_word: "candle",
    points: 1000,
    level: 57,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Tomb, Thai, Cold, Stone, Pad, Land, ",
    compoundled: "Tomb, Stone, Cold, Shoulder, Pad, Thai, Land",
    correct_order: "0,3,2,6,4,1,5",
    hidden_word: "shoulder",
    points: 1000,
    level: 58,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Beer, Pure, Craft, , Bong, Maker, Pleasure",
    compoundled: "Pure, Pleasure, Craft, Beer, Bong, Hit, Maker",
    correct_order: "1,6,2,0,4,3,5",
    hidden_word: "hit",
    points: 1000,
    level: 59,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Back, Herb, Unit, Garden, Message, , Away",
    compoundled: "Herb, Garden, Unit, Circle, Back, Away, Message",
    correct_order: "1,3,2,5,0,6,4",
    hidden_word: "circle",
    points: 1000,
    level: 60,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Jug, Down, Chug, Bad, Head, Vibes, ",
    compoundled: "Chug, Jug, Head, Count, Down, Bad, Vibes",
    correct_order: "2,0,4,6,1,3,5",
    hidden_word: "count",
    points: 1000,
    level: 61,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Think, Unlikely, Highly, , Pair, Off, Beam",
    compoundled: "Think, Unlikely, Highly, Balance, Pair, Off, Beam",
    correct_order: "0,2,1,4,5,3,6",
    hidden_word: "balance",
    points: 1000,
    level: 62,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Nurse, , Chip, Couch, Depth, Charge, In",
    compoundled: "Nurse, Potato, Chip, Couch, Depth, Charge, In",
    correct_order: "3,1,2,6,4,5,0",
    hidden_word: "potato",
    points: 1000,
    level: 63,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Deductible, Conspicuous, Tax, Amount, Dilligence, , Consumption",
    compoundled:
      "Deductible, Conspicuous, Tax, Amount, Dilligence, Due, Consumption",
    correct_order: "1,6,2,0,3,5,4",
    hidden_word: "due",
    points: 1000,
    level: 64,
    upload_date: "2023-11-06 11:30:00",
  },
  {
    words: "Shy, Bug, Empty, Spray, Stomach, , Paint",
    compoundled: "Empty, Stomach, Bug, Spray, Paint, Gun, Shy",
    correct_order: "2,4,1,3,6,5,0",
    hidden_word: "gun",
    points: 1000,
    level: 65,
    upload_date: "11/11/2023",
  },
];

const seedGameTable = () => Game.bulkCreate(gameData);

module.exports = seedGameTable;
